name: iOS CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '12.4' # Specify your Xcode version here

    - name: Install dependencies
      run: |
        gem install cocoapods
        pod install

    - name: Build and Test
      run: |
        xcodebuild -workspace YourWorkspaceName.xcworkspace -scheme YourSchemeName -destination 'platform=iOS Simulator,name=iPhone 12,OS=14.4' build test
